version: '3'
services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: yourpassword
    volumes:
      - oracle_data:/opt/oracle/oradata
    # Ограничение ресурсов (опционально)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
volumes:
  oracle_data: