version: '3'
services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: yourpassword
    volumes:
      - oracle_data:/opt/oracle/oradata
volumes:
  oracle_data: