version: '3'
services:
  oracle:
    image: gvenzl/oracle-free:slim-faststart
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: yourpassword
    volumes:
      - oracle_data:/opt/oracle/oradata
    # Ограничение ресурсов (опционально)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
volumes:
  oracle_data:
